### ISSUE TITLE
[Build Prod] transition shorthand unit lost when Angular-CLI 6.2.x

### ISSUE THREAD

**Issue by HsuanXyz** [angular/angular-cli#12408]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### Command (mark with an `x`)
```
- [ ] new
- [x] build
- [ ] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] xi18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc
```

### Versions

```
Angular CLI: 6.2.3
Node: 10.0.0
OS: darwin x64
Angular: 6.1.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.8.3
@angular-devkit/build-angular     0.8.3
@angular-devkit/build-optimizer   0.8.3
@angular-devkit/build-webpack     0.8.3
@angular-devkit/core              0.8.3
@angular-devkit/schematics        0.8.3
@angular/cli                      6.2.3
@ngtools/webpack                  6.2.3
@schematics/angular               0.8.3
@schematics/update                0.8.3
rxjs                              6.2.2
typescript                        2.9.2
webpack                           4.20.2
```

### Repro steps

Repro: https://github.com/HsuanXyz/issues-ng-cli-6.2.x-clean-css-

```css
/* input this */
.class {
  transition: opacity .3s linear, height 0s ease .3s;
}

/* ng build --prod */
.class{transition:opacity .3s linear,height .3s}
```

### The log given by the failure

*

### Desired functionality

```css
/* input this */
.class {
  transition: opacity .3s linear, height 0s ease .3s;
}

/* ng build --prod */
.class{transition: opacity .3s linear, height 0s ease .3s}
```

### Mention any other details that might be useful

NG-ZORRO PR: https://github.com/NG-ZORRO/ng-zorro-antd/pull/2163

clean-css issues: https://github.com/jakubpawlowicz/clean-css/issues/1050

Reproduction: https://github.com/HsuanXyz/issues-ng-cli-6.2.x-clean-css-
