### ISSUE TITLE
Issue with optimize-css-webpack-plugin with --prod build

### ISSUE THREAD

**Issue by jrdutton** [angular/angular-cli#17042]
# 🐞 bug report

### Is this a regression?
This only appears in a production build with Angular 9. It did not appear in Angular 8.
### Description
When building with the --prod flag, an unhandled exception is occurring at the optimize-css-webpack-plugin stage.

I've looked in the styles js files within the dist folder and can find this: 

.form-control {\n  display: block;\n  width: 100%;\n  height: calc(1.5em + 0.75rem2px);

And this appears to come from the bootstrap package CSS code:

<pre><code>
.form-control {
  display: block;
  width: 100%;
  height: calc(1.5em + 0.75rem + 2px);
  padding: 0.375rem 0.75rem;
  font-size: 1rem;
  font-weight: 400;
  line-height: 1.5;
  color: #495057;
  background-color: #fff;
  background-clip: padding-box;
  border: 1px solid #ced4da;
  border-radius: 0.25rem;
  transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
}
</code></pre>

## 🔥 Exception or Error
<pre><code>
[error] JisonParserError: Parse error on line 1: 
1.5em + 0.75rem2px
---------^
Expecting end of input, "RPAREN", "ADD", "SUB", "MUL", "DIV", got unexpected "UNKNOWN_DIMENSION"
    at <my file path>\styles.ea6bdcac0bc9743c059a.css:6:25533
    at Parser.parseError (<my file path>\node_modules\postcss-calc\dist\parser.js:1200:15)
    at Parser.parse (<my file path>\node_modules\postcss-calc\dist\parser.js:1716:30)
    at <my file path>\node_modules\postcss-calc\dist\lib\transform.js:33:30
    at walk (<my file path>\node_modules\postcss-value-parser\lib\walk.js:7:16)
    at ValueParser.walk (<my file path>\node_modules\postcss-value-parser\lib\index.js:18:3)
    at transformValue (<my file path>\node_modules\postcss-calc\dist\lib\transform.js:24:50)
    at _default (<my file path>\node_modules\postcss-calc\dist\lib\transform.js:66:100)
    at <my file path>\node_modules\postcss-calc\dist\index.js:27:32
    at <my file path>\node_modules\postcss\lib\container.js:135:18
    at Rule.each (<my file path>\node_modules\postcss\lib\container.js:101:16)
    at Rule.walk (<my file path>\node_modules\postcss\lib\container.js:131:17)
    at <my file path>\node_modules\postcss\lib\container.js:148:24
    at Root.each (<my file path>\node_modules\postcss\lib\container.js:101:16)
    at Root.walk (<my file path>\node_modules\postcss\lib\container.js:131:17)
    at <my file path>\node_modules\postcss-calc\dist\index.js:23:9
    at initializePlugin (<my file path>\node_modules\cssnano\dist\index.js:31:51)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
</code></pre>
## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 9.0.3
Node: 12.13.1
OS: win32 x64

Angular: 9.0.2
... animations, common, compiler, compiler-cli, core, forms
... language-service, localize, platform-browser
... platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.3
@angular-devkit/build-angular     0.900.3
@angular-devkit/build-optimizer   0.900.3
@angular-devkit/build-webpack     0.900.3
@angular-devkit/core              8.3.22
@angular-devkit/schematics        8.3.22
@angular/cli                      9.0.3
@ngtools/webpack                  9.0.3
@schematics/angular               9.0.3
@schematics/update                0.900.3
rxjs                              6.5.4
typescript                        3.7.5
webpack                           4.41.2
</code></pre>

**Comment by alan-agius4** [comment]
Hi @jrdutton, I tried to reproduce this locally however I am failing.

Adding the below
```css
/* You can add global styles to this file, and also import other style files */
.form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + 0.75rem + 2px);
    padding: 0.375rem 0.75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da;
    border-radius: 0.25rem;
    transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
  }
```

Produces the following without an error
```
.form-control{display:block;width:100%;height:calc(1.5em + .75rem + 2px);padding:.375rem .75rem;font-size:1rem;font-weight:400;line-height:1.5;color:#495057;background-color:#fff;background-clip:padding-box;border:1px solid #ced4da;border-radius:.25rem;-webkit-transition:border-color .15s ease-in-out,box-shadow .15s ease-in-out;transition:border-color .15s ease-in-out,box-shadow .15s ease-in-out}
```

Can you setup a minimal repro please? A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.
