### ISSUE TITLE
TypeError: Cannot read property 'raws' of undefined processing styles.scss after migrating from v11 to v12.0.3

### ISSUE THREAD

**Issue by pietschy** [angular/angular-cli#21055]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Description

We're getting this error after upgrading from 11 to 12.  

It's also only failing for one of our apps in a multi app build. The `style.scss` file in the failing app is the same as those in other apps that are building fine.

## 🔬 Minimal Reproduction

Happy to do further investigation if required.  

## 🔥 Exception or Error

<pre><code>
......./src/styles.scss - Error: Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
TypeError: Cannot read property 'raws' of undefined
    at Parser.space (....../node_modules/postcss-values-parser/lib/parser.js:387:25)
    at Parser.parseTokens (....../node_modules/postcss-values-parser/lib/parser.js:223:14)
    at Parser.loop (....../node_modules/postcss-values-parser/lib/parser.js:132:12)
    at Parser.parse (....../node_modules/postcss-values-parser/lib/parser.js:51:17)
    at parse (....../node_modules/postcss-custom-properties/index.cjs.js:47:30)
    at ....../node_modules/postcss-custom-properties/index.cjs.js:73:42
    at Array.forEach (<anonymous>)
    at ....../node_modules/postcss-custom-properties/index.cjs.js:69:26
    at Array.forEach (<anonymous>)
    at getCustomPropertiesFromRoot (....../node_modules/postcss-custom-properties/index.cjs.js:65:22)
    at Object.syncTransform [as plugin] (....../node_modules/postcss-custom-properties/index.cjs.js:519:30)
    at ....../node_modules/postcss-preset-env/index.js:443:97
    at async LazyResult.runAsync (....../node_modules/postcss/lib/lazy-result.js:388:11)
    at async Object.loader (....../node_modules/postcss-loader/dist/index.js:87:14)
    at processResult (....../node_modules/webpack/lib/NormalModule.js:703:19)
    at ....../node_modules/webpack/lib/NormalModule.js:809:5
    at ....../node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at ....../node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (....../node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (....../node_modules/postcss-loader/dist/index.js:96:7)
</code></pre>

## 🌍 Your Environment

<pre><code>
$ ng --version
12.3.6
</code></pre>

**Anything else relevant?**

We're also getting the following warning while building.

```
Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.0, but postcss-preset-env uses 7.0.35. Perhaps this is the source of the error below.
```
I've tried deleting node modules and lock file but I still get the same error.  I don't appear to have any other dependencies involved.

```
$ npm ls postcss-preset-env
@.........
└─┬ @angular-devkit/build-angular@12.0.3
  └── postcss-preset-env@6.7.0 
```
```
$ npm ls postcss
@.........
└─┬ @angular-devkit/build-angular@12.0.3
  ├─┬ css-loader@5.2.4
  │ └── postcss@8.3.0  deduped
  ├─┬ css-minimizer-webpack-plugin@3.0.0
  │ └── postcss@8.3.0  deduped
  ├── postcss@8.3.0 
  ├─┬ postcss-preset-env@6.7.0
  │ ├─┬ autoprefixer@9.8.6
  │ │ └── postcss@7.0.35 
  │ ├─┬ css-blank-pseudo@0.1.4
  │ │ └── postcss@7.0.35 
  │ ├─┬ css-has-pseudo@0.10.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ css-prefers-color-scheme@3.1.1
  │ │ └── postcss@7.0.35 
  │ ├── postcss@7.0.35 
  │ ├─┬ postcss-attribute-case-insensitive@4.0.2
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-color-functional-notation@2.0.1
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-color-gray@5.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-color-hex-alpha@5.0.3
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-color-mod-function@3.0.3
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-color-rebeccapurple@4.0.1
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-custom-media@7.0.8
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-custom-properties@8.0.11
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-custom-selectors@5.1.2
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-dir-pseudo-class@5.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-double-position-gradients@1.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-env-function@2.0.2
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-focus-visible@4.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-focus-within@3.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-font-variant@4.0.1
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-gap-properties@2.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-image-set-function@3.0.1
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-initial@3.0.4
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-lab-function@2.0.1
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-logical@3.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-media-minmax@4.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-nesting@7.0.1
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-overflow-shorthand@2.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-page-break@2.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-place@4.0.1
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-pseudo-class-any-link@6.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-replace-overflow-wrap@3.0.0
  │ │ └── postcss@7.0.35 
  │ ├─┬ postcss-selector-matches@4.0.0
  │ │ └── postcss@7.0.35 
  │ └─┬ postcss-selector-not@4.0.1
  │   └── postcss@7.0.35 
  └─┬ resolve-url-loader@4.0.0
    └── postcss@7.0.35 

```

**Comment by alan-agius4** [comment]
This looks like a package hoisting issue. 

Which version of NPM are you using? NPM 7 had several hoisting defects, I suggest that you either try to update to the latest version to NPM 7 if you are not using the latest version. 

If the problem persists after updating, try downgrading to NPM 6 or use an alternate package manager.

**Comment by elion** [comment]
I get the same error using Yarn 1.22.10:

```
Unknown error from PostCSS plugin. Your current PostCSS version is 8.3.0, but postcss-preset-env uses 7.0.35. Perhaps this is the source of the error below.
```

**Comment by alan-agius4** [comment]
Can you try to run the below and see if the issue persists?

```
rm -rf node_modules yarn.lock
yarn
```

**Comment by pietschy** [comment]
We're using 
```
$ node  --version
v12.16.3

w$ npm --version
6.14.4
```

I'll try updating npm and see how I go.

**Comment by pietschy** [comment]
Updated to 
```
$ npm --version 
7.16.0
```
but still getting the same error.

I started commenting out lines to see what triggered it.  The two commented out lines in the following scss file will trigger the bug for us.  But only in one of our apps.  It's fine in all of the others.
```scss
@use '~@angular/material' as mat;

// Include the common styles for Angular Material. We include this here so that you only
// have to load a single css file for Angular Material in your app.
// Be sure that you only ever include this mixin once!
@include mat.core();

$primary-palette: mat.define-palette(mat.$indigo-palette);
$accent-palette:  mat.define-palette(mat.$pink-palette, A200, A100, A400);
$warn-palette:    mat.define-palette(mat.$red-palette);
$theme: mat.define-light-theme($primary-palette, $accent-palette, $warn-palette);

@include mat.all-component-themes($theme);

:root {
  --theme-primary-color: #{mat.get-color-from-palette(map-get($theme, primary))};

  // Uncommenting either of the following two lines will trigger the error.  But only in one of our apps
  //--theme-foreground-color: #{mat.get-color-from-palette(map-get($tester-app-theme, foreground))};
  //--theme-background-color: #{mat.get-color-from-palette(map-get($tester-app-theme, background))};

  --theme-warn-color: #{mat.get-color-from-palette(map-get($theme, warn))};
  --theme-warn-background-color: #{mat.get-color-from-palette(map-get($theme, warn))};
  --theme-warn-color-default-contrast: #{mat.get-color-from-palette(map-get($theme, warn), default-contrast)};
  --theme-selected-item-background-color: #{mat.get-color-from-palette(map-get($theme, primary), 0.15)};
  --theme-selected-item-border-color: #{mat.get-color-from-palette(map-get($theme, primary), 0.6)};
  --theme-selected-item-background-hover-color: #{mat.get-color-from-palette(map-get($theme, primary), 0.05)};
}


```

**Comment by alan-agius4** [comment]
@pietschy, I am unable to replicate the issue with the code above.  Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by pietschy** [comment]
Hi @alan-agius4, I've create a repo at https://github.com/Coolon/angular-12-bug-21055

It's reproducing the error for me and for a colleague  If you need any more info let me know.

Thanks

**Comment by alan-agius4** [comment]
I debugged this by adding some debug statements in SCSS.

```scss
  @debug "map-get($theme, foreground)";
  @debug map-get($theme, foreground);

  @debug "mat.get-color-from-palette(map-get($theme, background))";
  @debug mat.get-color-from-palette(map-get($theme, background));
```

The above produces the following 
```
apps/gateway/provisioning/src/styles/theme.scss:17 DEBUG: (50: #e8eaf6, 100: #c5cae9, 200: #9fa8da, 300: #7986cb, 400: #5c6bc0, 500: #3f51b5, 600: #3949ab, 700: #303f9f, 800: #283593, 900: #1a237e, A100: #8c9eff, A200: #536dfe, A400: #3d5afe, A700: #304ffe, contrast: (50: rgba(0, 0, 0, 0.87), 100: rgba(0, 0, 0, 0.87), 200: rgba(0, 0, 0, 0.87), 300: white, 400: white, 500: white, 600: white, 700: white, 800: white, 900: white, A100: rgba(0, 0, 0, 0.87), A200: white, A400: white, A700: white), default: #3f51b5, lighter: #c5cae9, darker: #303f9f, text: #3f51b5, default-contrast: white, lighter-contrast: rgba(0, 0, 0, 0.87), darker-contrast: white, "50-contrast": rgba(0, 0, 0, 0.87), "100-contrast": rgba(0, 0, 0, 0.87), "200-contrast": rgba(0, 0, 0, 0.87), "300-contrast": white, "400-contrast": white, "500-contrast": white, "600-contrast": white, "700-contrast": white, "800-contrast": white, "900-contrast": white, "A100-contrast": rgba(0, 0, 0, 0.87), "A200-contrast": white, "A400-contrast": white, "A700-contrast": white, "contrast-contrast": null)
apps/gateway/provisioning/src/styles/theme.scss:20 DEBUG: map-get($theme, foreground)
apps/gateway/provisioning/src/styles/theme.scss:21 DEBUG: (base: black, divider: rgba(0, 0, 0, 0.12), dividers: rgba(0, 0, 0, 0.12), disabled: rgba(0, 0, 0, 0.38), disabled-button: rgba(0, 0, 0, 0.26), disabled-text: rgba(0, 0, 0, 0.38), elevation: black, hint-text: rgba(0, 0, 0, 0.38), secondary-text: rgba(0, 0, 0, 0.54), icon: rgba(0, 0, 0, 0.54), icons: rgba(0, 0, 0, 0.54), text: rgba(0, 0, 0, 0.87), slider-min: rgba(0, 0, 0, 0.87), slider-off: rgba(0, 0, 0, 0.26), slider-off-active: rgba(0, 0, 0, 0.38))
apps/gateway/provisioning/src/styles/theme.scss:23 DEBUG: mat.get-color-from-palette(map-get($theme, background))
apps/gateway/provisioning/src/styles/theme.scss:24 DEBUG: null
```

`mat.get-color-from-palette(map-get($theme, background))` produces a null value, but since you are interpolating it using `#{}` it will still emit the variable but without a value set. `postcss-values-parser` cannot parse this and crashes.

```css
:root {
  --theme-background-color: ;
}
```

I don't know what is the reason of the interpolation in the first place, but removing the interpolation will cause the the variables with `null` value not to be defined at all.

While I don't think having an empty value is desired here, I suggest to file an issue with `postcss-values-parser` to handle this more gracefully.
