### ISSUE TITLE
Live reloading not working with Docker

### ISSUE THREAD

**Issue by pacocom** [angular/angular-cli#21904]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

No

### Description

Live Reloading enabled not working, I have Windows 10 + Docker version 20.10.8, build 3967b7d

Dockerfile.dev
```
FROM node:14.17

ARG WORK_DIR=/frontend
ENV PATH ${WORK_DIR}/node_modules/.bin:$PATH

RUN mkdir ${WORK_DIR}
WORKDIR ${WORK_DIR}

COPY package.json ${WORK_DIR}
COPY package-lock.json ${WORK_DIR}

RUN npm install @angular/cli
RUN npm install

COPY . ${WORK_DIR}

EXPOSE 4200

CMD ng serve --host 0.0.0.0
```
docker-compose.yml
```
version: '3.9' # optional since v1.27.0
services:
  docker-frontend:
    build:
      context: angular-crash-2021
      dockerfile: Dockerfile.dev
    ports:
      - '4200:4200'
    volumes:
      - ./angular-crash-2021/src:/frontend/src
```

### Please provide a link to a minimal reproduction of the bug

https://github.com/pacocom/angular12-docker-not-working-hot-reloading.git

### Please provide the environment you discovered this bug in

```
Angular CLI: 12.2.8
Node: 14.18.0
Package Manager: npm 7.24.2
OS: linux x64

Angular:
...

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.1202.8 (cli-only)
@angular-devkit/core         12.2.8 (cli-only)
@angular-devkit/schematics   12.2.8 (cli-only)
@schematics/angular          12.2.8 (cli-only)
```
