### ISSUE TITLE
Cannot set the color of anything with a stylesheet.

### ISSUE THREAD

**Issue by AnnoyingB** [angular/angular-cli#22243]
Whenever I try to set the background color, it doesn't change. I tried changing the file from scss to css but there is no difference. Also, when I try to set the color of the border, it just stays white, I also can set the font. Please help, Many thanks.

Code:

home.component.html
``` html
<body>
    <div class="main-div">
        <div class="upper-div">
            <p>Lorem ispum</p>
            <br>
        </div>
    </div>
</body>
```

home.component.ts
``` ts
import { Component, OnInit, ViewEncapsulation } from '@angular/core';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class HomeComponent implements OnInit {

  constructor() { }

  ngOnInit(): void {
  }

}
```

home.component.scss:
``` scss
div.upper-div{
    font-style: italic;
    background-color: red;
    width: 98.5vw;
    border: 5px solid salmon;
    padding-left: 0rem;
}

:host{
    background-color: salmon;
}
```
