### ISSUE TITLE
@import in css doesn't apply cascade layer to media queries

### ISSUE THREAD

**Issue by Th3S4mur41** [angular/angular-cli#23806]
# 🐞 Bug report

### Command (mark with an `x`)

- [ ] new
- [x] build
- [x] serve
- [ ] test
- [ ] e2e
- [ ] generate
- [ ] add
- [ ] update
- [ ] lint
- [ ] extract-i18n
- [ ] run
- [ ] config
- [ ] help
- [ ] version
- [ ] doc

### Is this a regression?

I don't think so

### Description

 A clear and concise description of the problem...

`@import url('external.css') layer(external);` should behave exactly the same as 

```
@layer internal {
 some CSS
}
```
As seeen in this [codepen](https://codepen.io/th3s4mur41/pen/MWVdBVm)

When Angular processes the import to include it in the main css file though, it doesn't put the @media queries from the external.css in the `@layer external` block.

## 🔬 Minimal Reproduction

Consider **main.css* being the angular app's main css file and external.css a CSS file imported from an external package.

```css
/* external.css */
@media (prefers-color-scheme: dark) {
  .import {
    background: darkgray;
  }
}
[data-theme="import-dark"] {
  background: black;
  color: white;
}
```

```css
/* main.css */
@import url('external.css') layer(external);

```

Compiling the angular app should result in the following CSS:

```css
/* expected-output.css */
@layer external {
  @media (prefers-color-scheme: dark) {
    .import {
      background: darkgray;
    }
  }
  [data-theme="import-dark"] {
    background: black;
    color: white;
  }
}
```

The actual output however is the following:
```css
/* wrong-output.css */
@media (prefers-color-scheme: dark) {
  .import {
    background: darkgray;
  }
}
@layer external {
  [data-theme="import-dark"] {
    background: black;
    color: white;
  }
}
```
