### ISSUE TITLE
ng test --no-watch not exiting in Continuous Integration (Github Actions)

### ISSUE THREAD

**Issue by simonchn160** [angular/angular-cli#24525]
### Command

test

### Is this a regression?

- [ ] Yes, this behavior used to work in the previous version

### Description

I added a step in my Github Actions workflow to run my Angular tests using the command `ng test` when a push occurs. The tests run and pass successfully but it never exits/moves onto the next step in my workflow. I've tried passing in the `--no-watch` and `--watch=false` flags into the command but that didn't fix the issue. I also set `singleRun: true` in my karma.conf.js file, which didn't work as well.

Here is my build-push.yml file:

```
name: Build PUSH only
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SHA: ${{ github.sha }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
    steps:
    - name: Checkout the PR
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
    - name: Install Angular CLI
      run: npm install --location=global @angular/cli@14.0.0
    - name: Install packages
      run: npm install
    - name: Build the UI
      run: ng build -c production
    - name: Run tests
      run: ng test --no-watch --no-progress --watch=false --code-coverage --browsers=ChromeHeadlessCI
```

Here is my karma.conf.js file:

```
module.exports = function (config)
{
    config.set({
        basePath           : '',
        frameworks         : ['jasmine', '@angular-devkit/build-angular'],
        plugins            : [
            require('karma-jasmine'),
            require('karma-chrome-launcher'),
            require('karma-jasmine-html-reporter'),
            require('karma-coverage'),
            require('@angular-devkit/build-angular/plugins/karma')
        ],
        client             : {
            jasmine     : {
                // you can add configuration options for Jasmine here
                // the possible options are listed at https://jasmine.github.io/api/edge/Configuration.html
                // for example, you can disable the random execution with `random: false`
                // or set a specific seed with `seed: 4321`
            },
            clearContext: false // leave Jasmine Spec Runner output visible in browser
        },
        jasmineHtmlReporter: {
            suppressAll: true // removes the duplicated traces
        },
        coverageReporter   : {
            dir      : require('path').join(__dirname, './coverage/fuse'),
            subdir   : '.',
            reporters: [
                {type: 'html'},
                {type: 'text-summary'}
            ]
        },
        reporters          : ['progress', 'kjhtml'],
        port               : 9876,
        colors             : true,
        logLevel           : config.LOG_INFO,
        autoWatch          : true,
        browsers           : ['ChromeHeadlessCI'],
        customLaunchers: {
            ChromeHeadlessCI: {
                base: 'ChromeHeadless',
                flags: ['--no-sandbox']
            }
        },
        singleRun          : true,
        restartOnFileChange: true,
        // Gives access to RohanSettings for tests
        files: [
            'scripts/for-docker/settings-template.js'
        ]
    });
};
```

Been stuck on this issue for several days with no luck. Any help is greatly appreciated!

### Minimal Reproduction

Running the command `ng test` works locally but when I make a push and the workflow is run, it never exits the tests.

### Your Environment

```text
_                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/

Angular CLI: 14.0.0
Node: 16.15.1
Package Manager: npm 8.11.0 
OS: darwin arm64

Angular: 13.0.1
... animations, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.1303.9
@angular-devkit/build-angular      13.3.9
@angular-devkit/core               13.3.9
@angular-devkit/schematics         14.0.0
@angular/cdk                       13.0.0
@angular/cli                       14.0.0
@angular/material                  13.0.0
@angular/material-moment-adapter   13.0.0
@schematics/angular                14.0.0
typescript                         4.4.4
```

### Anything else relevant?

Here's a link to the gist I created which contains the logs displayed from the workflow: 
https://gist.github.com/simonchn160/91aac08635daf873bfb1bc276d2a9a12

**Comment by acorlin6** [comment]
Same, my tests haven't been exiting in CI with github actions

**Comment by alan-agius4** [comment]
Hi @simonchn160, I am unable to replicate using the steps provided. See: https://github.com/alan-agius4/test-gh-actions/actions/runs/3901482704/jobs/6663380376

Can you setup a minimal repro please?

You can read [here](https://github.com/angular/angular-cli/blob/master/CONTRIBUTING.md#-submitting-an-issue) why this is needed. A good way to make a minimal repro is to create a new app via `ng new repro-app` and adding the minimum possible code to show the problem. Then you can push this repository to github and link it here.

This might be related to your directory structure so its really important to get an accurate repro to diagnose this.

**Comment by alan-agius4** [comment]
Can you try to update the action to the below to not rely on a global CLI? Alternatively update the global CLI to a more recent version instead of `14.0.0` as this issue is likely a duplicate of https://github.com/angular/angular-cli/issues/23289.

```yaml
name: Build PUSH only
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        SHA: ${{ github.sha }}
        REPO: ${{ github.repository }}
        BRANCH: ${{ github.ref_name }}
    steps:
    - name: Checkout the PR
      uses: actions/checkout@v3
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install Azure CLI
      run: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash 
    - name: Install packages
      run: npm install
    - name: Build the UI
      run: ng build -c production
    - name: Run tests
      run: npm run ng test -- --no-watch --no-progress --watch=false --code-coverage --browsers=ChromeHeadlessCI
```
