### ISSUE TITLE
esbuild: not properly using postcss/browserlist?

### ISSUE THREAD

**Issue by plessbd** [angular/angular-cli#25257]
### Command

serve

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### Description

when trying out
```json
 "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
```
with browserlistrc
```
last 2 versions
not dead
not IE 11 # Angular supports IE 11 only as an opt-in. To opt-in, remove the 'not' prefix on this line.
```

There is a difference between the "css" that is generated

### Minimal Reproduction

source:
```scss
.cross {
    mask: url("/assets/legend/d3-cross.svg") no-repeat 50% 50%;
}
.circle {
    mask: url("/assets/legend/d3-circle.svg") no-repeat 50% 50%;
}
.wye {
    mask: url("/assets/legend/d3-wye.svg") no-repeat 50% 50%;
}
.square {
    mask: url("/assets/legend/d3-square.svg") no-repeat 50% 50%;
}
.triangle {
    mask: url("/assets/legend/d3-triangle.svg") no-repeat 50% 50%;
}
.diamond {
    mask: url("/assets/legend/d3-diamond.svg") no-repeat 50% 50%;
}
.star {
    mask: url("/assets/legend/d3-star.svg") no-repeat 50% 50%;
}
```

with browser-esbuild:
```css
.cross[_ngcontent-%COMP%] {
  mask: url(/assets/legend/d3-cross.svg) no-repeat 50% 50%;
}
.circle[_ngcontent-%COMP%] {
  mask: url(/assets/legend/d3-circle.svg) no-repeat 50% 50%;
}
.wye[_ngcontent-%COMP%] {
  mask: url(/assets/legend/d3-wye.svg) no-repeat 50% 50%;
}
.square[_ngcontent-%COMP%] {
  mask: url(/assets/legend/d3-square.svg) no-repeat 50% 50%;
}
.triangle[_ngcontent-%COMP%] {
  mask: url(/assets/legend/d3-triangle.svg) no-repeat 50% 50%;
}
.diamond[_ngcontent-%COMP%] {
  mask: url(/assets/legend/d3-diamond.svg) no-repeat 50% 50%;
}
.star[_ngcontent-%COMP%] {
  mask: url(/assets/legend/d3-star.svg) no-repeat 50% 50%;
}
```

with browser:
```css
.cross[_ngcontent-%COMP%] {
  -webkit-mask: url("/assets/legend/d3-cross.svg") no-repeat 50% 50%;
          mask: url("/assets/legend/d3-cross.svg") no-repeat 50% 50%;
}

.circle[_ngcontent-%COMP%] {
  -webkit-mask: url("/assets/legend/d3-circle.svg") no-repeat 50% 50%;
          mask: url("/assets/legend/d3-circle.svg") no-repeat 50% 50%;
}

.wye[_ngcontent-%COMP%] {
  -webkit-mask: url("/assets/legend/d3-wye.svg") no-repeat 50% 50%;
          mask: url("/assets/legend/d3-wye.svg") no-repeat 50% 50%;
}

.square[_ngcontent-%COMP%] {
  -webkit-mask: url("/assets/legend/d3-square.svg") no-repeat 50% 50%;
          mask: url("/assets/legend/d3-square.svg") no-repeat 50% 50%;
}

.triangle[_ngcontent-%COMP%] {
  -webkit-mask: url("/assets/legend/d3-triangle.svg") no-repeat 50% 50%;
          mask: url("/assets/legend/d3-triangle.svg") no-repeat 50% 50%;
}

.diamond[_ngcontent-%COMP%] {
  -webkit-mask: url("/assets/legend/d3-diamond.svg") no-repeat 50% 50%;
          mask: url("/assets/legend/d3-diamond.svg") no-repeat 50% 50%;
}

.star[_ngcontent-%COMP%] {
  -webkit-mask: url("/assets/legend/d3-star.svg") no-repeat 50% 50%;
          mask: url("/assets/legend/d3-star.svg") no-repeat 50% 50%;
}
```

### Exception or Error

```text
the outputted "css" is missing the webkit specific css
```

### Your Environment

```text
Angular CLI: 16.0.2
Node: 18.15.0
Package Manager: npm 9.6.2
OS: linux x64

Angular: 16.0.2
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1600.2
@angular-devkit/build-angular   16.0.2
@angular-devkit/core            16.0.2
@angular-devkit/schematics      16.0.2
@angular/cdk                    16.0.1
@angular/material               16.0.1
@schematics/angular             16.0.2
rxjs                            7.8.1
typescript                      5.0.4
```
