### ISSUE TITLE
Error: ENAMETOOLONG: name too long

### ISSUE THREAD

**Issue by aayaresko** [angular/angular-cli#2585]
> ## Please provide us with the following information:
### OS?

> Windows 7, 8 or 10. Linux (which distribution). Mac OSX (Yosemite? El Capitan?)

Linux main 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u1 (2016-09-03) x86_64 GNU/Linux
### Versions.

> Please run `ng --version`. If there's nothing outputted, please run in a Terminal: `node --version` and paste the result here:

angular-cli: 1.0.0-beta.16
node: 6.7.0
os: linux x64
### Repro steps.

> Was this an app that wasn't created using the CLI? What change did you do on your code? etc.

my app was created using CLI. the problem is that when I trying to execute `ng build --aot` the build process fails. apparently compiler has problems with `any.component.css` which contains: 

``` css
html, body {
    height: 100%;
}

body {
    margin: 0;
    padding: 0;
    width: 100%;
    color: #B0BEC5;
    display: table;
    font-weight: 100;
}

.container {
    text-align: center;
    display: table-cell;
    vertical-align: middle;
}

.content {
    text-align: center;
    display: inline-block;
}

.title {
    font-size: 63px;
    margin: 10px auto;
}

h1 {
    font-size: 350px;
    margin: 10px auto;
}
```

my component consists of `any.component.html`, `any.component.css`, `any.component.ts`.
### The log given by the failure.

> Normally this include a stack trace and some more information.

``` javascript
ng build --aot
Could not start watchman; falling back to NodeWatcher for file s5130ms building modules                                                                                                            1ms add1m977ms 167ms asset 95% emitting
Error: ENAMETOOLONG: name too long, open '/www/angular/dist/html, body {                                                                                                         
    height: 100%;
}

body {
    margin: 0;
    padding: 0;
    width: 100%;
    color: #B0BEC5;
    display: table;
    font-weight: 100;
}

.container {
    text-align: center;
    display: table-cell;
    vertical-align: middle;
}

.content {
    text-align: center;
    display: inline-block;
}

.title {
    font-size: 63px;
    margin: 10px auto;
}

h1 {
    font-size: 350px;
    margin: 10px auto;
}.map'
    at Error (native)

/www/angular/node_modules/webpack/lib/Compiler.js:203
                                                if(err) return callback(err);
                     ^
TypeError: Cannot read property 'hash' of undefined
    at /www/angular/node_modules/angular-cli/tasks/build-webpack.js:38:26
    at Compiler.<anonymous> (/www/angular/node_modules/webpack/lib/Compiler.js:203:22)
    at Compiler.<anonymous> (/www/angular/node_modules/webpack/lib/Compiler.js:302:19)
    at /www/angular/node_modules/webpack/node_modules/async/lib/async.js:52:16
    at done (/www/angular/node_modules/webpack/node_modules/async/lib/async.js:241:17)
    at /www/angular/node_modules/webpack/node_modules/async/lib/async.js:44:16
    at fs.js:1305:7
    at FSReqWrap.oncomplete (fs.js:123:15)
```
### Mention any other details that might be useful.

It's easy to reproduce: create a new app with dummy component. create a separate `component.css` file for that component. fill `component.css` file with some styles.

thanx in advance!
