### ISSUE TITLE
[browser-esbuild] add ability to configure processed assets output folder name

### ISSUE THREAD

**Issue by MarcoGlauser** [angular/angular-cli#26057]
### Command

build

### Description

The esbuild builder will hash asset filenames that are imported from css and put them in the `/media` folder. 
```css
.test {
    background: url('assets/images/next-arrow.svg') center no-repeat;
}
```
Will be transformed into the following:
```css
.test {
    background: url('./media/next-arrow.CZQC2LXJ.svg') center no-repeat;
}
```

While this is a nice feature for cache busting, it clashes with our django server that also serves a `/media` folder. 
For the sake of not breaking existing urls, it would be nice, if there was a way to configure this folder name.
We tried the `resourcesOutputPath` option but that doesn't seem to have any effect. 

### Describe the solution you'd like

It would be great if there was a way to configure the name of the processed asset output folder.

### Describe alternatives you've considered

We can change the media folder for django. However, that would break existing links and I think that the folder name should not be hardcoded in the first place.
