### ISSUE TITLE
Import of css modules as external css

### ISSUE THREAD

**Issue by nnaydenow** [angular/angular-cli#26964]
### Which @angular/* package(s) are the source of the bug?

common, core

### Is this a regression?

Yes

### Description

Third party that I'm using provide css files with .module.css extension . I'm registering in `angular.json >project > angular-app > architect > build > options > styles `these files as styles to be imported directly in the global so I can consume them in the application without any suffixes and prefixes:
```json
{
  ....
      "architect": {
        "build": {
          "options": {
            "styles": [
              "src/styles.css",
              "thirparty_module/ExternalStyles.module.css",
            ],
  ....
```

Then I'm adding these imports in `src/styles.css` using `@use`

```css
/* You can add global styles to this file, and also import other style files */
@use '@ui5/webcomponents/dist/styles/Input.module.css';
```

But when I inspect the inject style element the styles look:
```css
/* src/styles.css */
@use "thirparty_module/ExternalStyles.module.css";

/* ../thirparty_module/ExternalStyles.module.css */
.Input_inputIcon {
```

Is it expected these modules to be processed because I read that these files are no longer processed due to webpack specific requirements?

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 17.1
```

**Comment by alan-agius4** [comment]
The stylesheet should only be imported once either in `style.css` or added to as part of the `styles` array. When referenced in both places it will effective cause it to be included twice in the generated stylesheet.

The `@use` is sass specific syntax and is not a valid semantic when used in `.css` files. If you want to import an external stylesheet in css the [`@import`](https://developer.mozilla.org/en-US/docs/Web/CSS/@import) should be used instead.

Closing as there doesn't appear to be any problem here.

**Comment by nnaydenow** [comment]
Hi @alan-agius4,

I reworked my imports and now I'm importing them with `@import` in the components styles and this seems to work but the file content is still changed for some reason.

```css
### third party css file named Input.module.css

.inputIcon {
  min-width: 1rem;
  min-height: 1rem;
}
```

```css
### angular component css named app.component.css

@import url("thirdparty-package/Input.module.css");

.class {
  background-color: red;
}
```

Everything results in:
```html
### web page opened on localhost:4200

<style>
  .Input_inputIcon[_ngcontent-ng-c214065838] {
    min-width: 1rem;
    min-height: 1rem;
  }

  .class[_ngcontent-ng-c214065838] {
    background-color: red;
  }
  /*# sourceMappingURL=app.component.css.map */
</style>
```

Seems like you removed the environment and the possibility to import CSS files as ECMA Script imports in version 14, but these files are treated still as modules, not as pure CSS.

Can you please check if this is the expected behaviour? If yes, could you please help me to find out how these files to not be processed as css modules because we want to use them as pure css then.

**Comment by nnaydenow** [comment]
I'm expecting the css from the import to be the same as it comes from the css file in the thirdparty package since I'm not able to import it as ECMA Script import in the java script and to use the generated scoped class name. In other frameworks you can import have following import

```js
import inputStyles from "thirdparty-package/Input.module.css"

console.log(inputStyles.inputIcon) => will result into Input_inputIcon
```

but with the current setup I'm expecting 

```css
<style>
  .inputIcon[_ngcontent-ng-c214065838] {
    min-width: 1rem;
    min-height: 1rem;
  }

  .class[_ngcontent-ng-c214065838] {
    background-color: red;
  }
  /*# sourceMappingURL=app.component.css.map */
</style>
``` 

instead of:

```css
<style>
  .Input_inputIcon[_ngcontent-ng-c214065838] {
    min-width: 1rem;
    min-height: 1rem;
  }

  .class[_ngcontent-ng-c214065838] {
    background-color: red;
  }
  /*# sourceMappingURL=app.component.css.map */
</style>
```
