### ISSUE TITLE
Could not resolve url("/assets/my-font.woff2") with angular 17

### ISSUE THREAD

**Issue by ThomasDevGif** [angular/angular-cli#27037]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Hello,

I upgraded my angular library project from angular 16 to angular 17 but the ng build command now throws :
`Could not resolve "/assets/my-font.woff2".`

I didn't find a solution so I created 2 new projects, one in angular 16 and one in angular 17, and only add the following code in the 2 projects :
```scss
@font-face {
  font-family: "my-font";
  src: url(/assets/my-font.woff2) format("woff2"),
  url(/assets/my-font.woff) format("woff");
}
```

I ran `npx ng build` in the 2 projects and only the angular 16 projects built successfully.

To fix the angular 17 project  I tried :

- using a scss variable (after reading #26339)
```scss
$font-url: "assets/my-font.woff";
$font-url2: "assets/my-font.woff2";

@font-face {
  font-family: "my-font";
  src: url($font-url2) format("woff2"),
  url($font-url) format("woff");
}
```

- Replace the urls with absolute or relative path like "../../assets/", "projects/my-lib/assets/", "assets/" or "/assets"

But the ng builld command still fail. Do I missed something ?

Thanks in advance

### Minimal Reproduction

- Create a angular 17 workspace with a library
- Add a `url("/assets/my-font.woff2")` in any scss file
- Run `ng build` command``

### Exception or Error

```text
Build failed with 1 errors
<stdin>:3:11: ERROR: Could not resolve "/assets/my-font.woff2"
```

### Your Environment

```text
Angular CLI: 17.1.2
Node: 18.19.0
Npm: 10.2.3
```
