### ISSUE TITLE
[ERROR] Could not resolve "../../assets/fonts/my-font.woff"

### ISSUE THREAD

**Issue by ThomasDevGif** [angular/angular-cli#27137]
### Command

build

### Is this a regression?

- [X] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

16

### Description

Hello,

Previously I opened an issue because I could't build my angular design system library after upgrading it fom v16 to v17.1.0 .
I had an error when importing my font when using absolute path : [ERROR] Could not resolve "/assets/fonts/my-font.woff".

I changed the ng-packagr version from v17.1.0 to 17.2.0 and my scss import using absolute path is now working.
But if I want to use relative path "../../assets/" it still does not compile.

Is there a reason to not allow relative path in scss import ?

I use my lib in several angular applications with different base href so the absolute path does not working.

Thanks in advance,

### Minimal Reproduction

- Create an angular 17 workspace
- Generate a design-system library
- Add some fonts in assets folder
- Create a styles folder :

projects / design-system /
-assets / fonts /...
-src / ...
-styles / fonts.scss

- Add the following code in the fonts.scss file
```scss
@font-face {
  font-family: "MyFont";
  src: url("../assets/fonts/my-font.woff2") format("woff2"),
  url("../assets/fonts/my-font.woff") format("woff");
}
```

- Try to run the `ng build` command

### Exception or Error

```text
[ERROR] Could not resolve "../assets/fonts/my-font.woff" [plugin angular-css-resource]
```

### Your Environment

```text
17.2.0
```
