### ISSUE TITLE
No Support for .cur cursor file loading

### ISSUE THREAD

**Issue by kgathi2** [angular/angular-cli#2733]
> ## Please provide us with the following information:
### OS?

> Mac OSX El Capitan
### Versions.

> ```
> version` and paste the result here:
> angular-cli: 1.0.0-beta.15
> node: 5.10.0
> os: darwin x64
> ```
### Repro steps.

> In a new project, add stylesheet referencing .cur cursor file
> [curs.zip](https://github.com/angular/angular-cli/files/532132/curs.zip)

``` css
    .left{
        cursor: url("assets/img/arrow-left.png"), url("assets/img/arrow-left.cur"), default !important;
    }
    .right{
        cursor: url("assets/img/arrow-right.png"), url("assets/img/arrow-right.cur"), default !important;
    }
```
### The log given by the failure.

> Normally this include a stack trace and some more information.

``` bash
ERROR in ./src/assets/img/arrow-right.cur
Module parse failed: /Users/superman/ngapp/src/assets/img/arrow-right.cur Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:103859-103898
 @ ./src/styles.scss
 @ multi styles

ERROR in ./src/assets/img/arrow-left.cur
Module parse failed: /Users/superman/ngapp/src/assets/img/arrow-left.cur Unexpected character '' (1:0)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./~/css-loader!./~/postcss-loader!./~/sass-loader!./src/styles.scss 6:103697-103735
 @ ./src/styles.scss
 @ multi styles
```
### Mention any other details that might be useful.

> ---
> 
> Thanks! We'll be in touch soon.
