### ISSUE TITLE
Missing vite dependency

### ISSUE THREAD

**Issue by bgotink** [angular/angular-cli#29921]
### Command

ø

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

18.2.13

### Description

https://github.com/angular/angular-cli/pull/29522 removed the vite dependency from `@angular-devkit/build-angular`, but that's a required peer dependency of `@vitejs/plugin-basic-ssl`.

![Image](https://github.com/user-attachments/assets/a34d35f1-40aa-47b3-8918-f1f95f811beb)

Currently we "fix" this in our projects by adding the following extension in yarn:

```yaml
packageExtensions:
  "@vitejs/plugin-basic-ssl@*":
    peerDependenciesMeta:
      vite:
        optional: true
```

### Minimal Reproduction

Use a strict package manager (e.g. yarn 4), install `@angular-devkit/build-angular`, notice warning.

### Exception or Error

```text

```

### Your Environment

```text
yarn 4, @angular-devkit/* 18.2.15
```
