### ISSUE TITLE
New Angular builder has issues with autoprefixer

### ISSUE THREAD

**Issue by waterplea** [angular/angular-cli#30302]
### Which @angular/* package(s) are the source of the bug?

Don't known / other

### Is this a regression?

Yes

### Description

When switching to Vite builder in Angular 18/19 it causes autoprefixer to stop working

### Please provide a link to a minimal reproduction of the bug

https://stackblitz.com/edit/stackblitz-starters-kycexs5v

### Please provide the exception or error you saw

```css
:host {
  width: stretch;
}
```
remains unprefixed

### Please provide the environment you discovered this bug in (run `ng version`)

```true
Angular 19 with new builder
```

### Anything else?

Here's the same blitz but with old builder:
https://stackblitz.com/edit/stackblitz-starters-ggd5ztxb
As you can see this style:
```css
:host {
  width: stretch;
}
```
is properly turned into this:
```css
[_nghost-ng-c1419874505] {
    width: -webkit-fill-available;
    width: -moz-available;
    width: stretch;
}
```
