### ISSUE TITLE
Erroneous web-server 404 warnings.

### ISSUE THREAD

**Issue by dailytabs** [angular/angular-cli#30568]
### Command

test

### Is this a regression?

- [x] Yes, this behavior used to work in the previous version

### The previous version in which this bug was not present was

latest 19.x

### Description

```
19 06 2025 20:46:57.963:WARN [web-server]: 404: /prototype/uJhB6kP9/First%20Last%20(Company).webp
19 06 2025 20:46:57.987:WARN [web-server]: 404: /base/media/InterVariable.woff2?v=4.1
19 06 2025 20:46:58.583:WARN [web-server]: 404: /prototype/8cW2pQzR/First%20Last%20(Company).webp
```

1. The 2 webp files **do exist** in public and work fine. This is a regression.
2. The font comes from `"inter-ui": "^4.1.0"`. This is a regression.

### Minimal Reproduction

1) Not sure, since they do exist and work fine!? They are the only assets I have with spaces in their names... Was this not accounted for in the update? I renamed to a simple, 1-word, a-z filename and the warning went away.
2) Adding the inter-ui package should be enough to trigger that. Might have to add to `style.scss`:
    ```scss
    @use "~inter-ui/default" with (
      $inter-font-display: swap,
      $inter-font-path: '~inter-ui/web'
    );
    
    @use "~inter-ui/variable" with (
      $inter-font-display: swap,
      $inter-font-path: '~inter-ui/variable'
    );
    
    @include default.all;
    @include variable.all;
    
    html { font-family: "Inter", "system-ui"; }
    
    @supports (font-variation-settings: normal) {
      html { font-family: "InterVariable", "system-ui"; }
    }
    ```

### Exception or Error

```text
19 06 2025 20:46:57.963:WARN [web-server]: 404: /prototype/uJhB6kP9/First%20Last%20(Company).webp
19 06 2025 20:46:57.987:WARN [web-server]: 404: /base/media/InterVariable.woff2?v=4.1
19 06 2025 20:46:58.583:WARN [web-server]: 404: /prototype/8cW2pQzR/First%20Last%20(Company).webp
```

### Your Environment

```text
Angular CLI: 20.0.3
Node: 22.16.0
Package Manager: npm 11.4.1
OS: linux x64

Angular: 
... 

Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.2000.3 (cli-only)
@angular-devkit/core         20.0.3 (cli-only)
@angular-devkit/schematics   20.0.3 (cli-only)
@schematics/angular          20.0.3 (cli-only)
```
