### ISSUE TITLE
Support sass mixin and variables within component style

### ISSUE THREAD

**Issue by MurhafSousli** [angular/angular-cli#4242]
Hi, Is it possible to use sass mixins and variables within component's style?

For instance I import bourbon in the main **style.scss**:

```css
/* You can add global styles to this file, and also import other style files */
@import '~normalize.css';
@import '~animate.css';
@import '~bourbon/app/assets/stylesheets/bourbon';
@import '~bourbon-neat/app/assets/stylesheets/neat';
```
I want to be able to do the following in **app.component.scss**
```css
:host{
  @include linear-gradient(to top, red, orange);
  background-color: $primary;
}
```
