### ISSUE TITLE
Able to use @at-root in component scss file when ViewEncapsulation set to Emulated

### ISSUE THREAD

**Issue by feng-xiao** [angular/angular-cli#9617]
### Versions
```
Angular CLI: 1.6.7
Node: 8.9.1
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router, service-worker

@angular/cli: 1.6.7
@angular/platform-server: error
@angular/tsc-wrapped: error
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.7.1
webpack: 3.10.0
```

### Repro steps
* Step 1
edit component scss file and add following
```scss
@at-root {
  html.test {
    .wizard {
      background-color: blue;
    }
  }
}
```

### Observed behavior
Generated output:
```scss
html.test[_ngcontent-c1]   .wizard[_ngcontent-c1] {
  background-color: blue; 
} 
```

### Desired behavior

It should be without [_ngcontent-c1] attribute on html.test selector. So the component can have different styles according to parent or root selector
```scss
html.test  .wizard[_ngcontent-c1] {
  background-color: blue; 
} 
```
