### ISSUE TITLE
Ng build fails. CssSyntaxError since 1.7.0-rc.0

### ISSUE THREAD

**Issue by elion** [angular/angular-cli#9642]
### Versions
Error occurs since v1.7.0-rc.0
```
Angular CLI: 1.7.0-rc.0
Node: 8.9.4
OS: win32 x64
Angular: 5.2.5
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.0-rc.0
@angular-devkit/build-optimizer: 0.3.1
@angular-devkit/core: 0.3.1
@angular-devkit/schematics: 0.3.1
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.0-rc.0
@schematics/angular: 0.3.1
@schematics/package-update: 0.3.1
typescript: 2.6.2
webpack: 3.10.0

```

### Observed behavior
```
ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./src/assets/styles/page.css
(Emitted value instead of an instance of Error) CssSyntaxError: C:\Users\{omitted}\angular-project\src\assets\styles\page.css:259:2159: Can't resolve '%23linearGradient-1' in 'C:\Users\{omitted}\angular-project\src\assets\styles'

> 259 |   background: transparent url("../img/icon.svg") no-repeat 50% 0;                                                                 ^
  260 | }

```

I get similar error messages for each svg file. The page.css is listed in angular-cli.json styles array.

### Repro steps
```
ng build
```

Possible breaking commits: 
https://github.com/angular/angular-cli/commit/4a745c9
https://github.com/angular/angular-cli/commit/fa175d8

**Comment by ShinDarth** [comment]
I can confirm this bug. I have exactly the same issue.

For me it appeared as soon as I updated to version 1.7, the issue was not in 1.6.

**Comment by emxjay** [comment]
Same here with v1.7.0.

**Comment by wonkim00** [comment]
1.7 is broken. Reverting to 1.6.

**Comment by nidhididi** [comment]
@wonkim00 did that work for you?

**Comment by hcornelison** [comment]
Same, 1.7.0 caused failing builds, pinned version to 1.6.0, builds are passing again.

**Comment by clydin** [comment]
This is caused by an issue with the processing of the content of certain url encoded inlined svgs.  Can someone experiencing this issue provide a minimal reproduction or an svg sample file that exhibits the problem?

**Comment by hcornelison** [comment]
@clydin I am unable to.

**Comment by wonkim00** [comment]
@nidhididi Yes. After deleting the node_modules folder, editing to "@angular/cli": "~1.6.0" in package.json, and running npm install again (which pulled cli 1.6.8), ng build ran successfully.

**Comment by nidhididi** [comment]
@wonkim00 thank you, I also had success with cli 1.6.8

**Comment by alfaproject** [comment]
I'm having the same issue and it's something to do with the `postcss-cli-resources` plugin. Apparently it doesn't quite support `background` properties with multiple backgrounds, being one of them an image.

Example:
```css
b {
  background:
    url('./assets/icons/columns.svg'),
    linear-gradient(to top, #0f322c 84%, #071a16 99%);
}
```

Will get compiled to:
```css
b {
  background: url('./assets/icons/columns.<hash>.svg');
}
```

**Comment by zygimantas** [comment]
I am getting the same error with single svg background url.

**Comment by smoke** [comment]
This is happening with SVG only.

**Comment by scandinave** [comment]
Happen with `src: local('Material Icons'), local('MaterialIcons-Regular'), url(../../assets/fonts/material-icon.woff2) format('woff2');` too

**Comment by embryologist** [comment]
> ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
> (Emitted value instead of an instance of Error) CssSyntaxError: /Users/json/OneDrive/MyProjects/ArtNgCore/node_modules/material-design-icons/iconfont/material-icons.css:10:12: Can't resolve '../node_modules/material-design-icons/iconfont/MaterialIcons-Regular.ttf)%20format(%27truetype%27' in '/Users/json/OneDrive/MyProjects/ArtNgCore/src'
> 
>    8 |        url(MaterialIcons-Regular.woff2) format('woff2'),
>    9 |        url(MaterialIcons-Regular.woff) format('woff'),
> > 10 |        url(MaterialIcons-Regular.ttf) format('truetype');
>      |            ^
>   11 | }
>   12 | 
> 
> ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
> (Emitted value instead of an instance of Error) CssSyntaxError: /Users/json/OneDrive/MyProjects/ArtNgCore/node_modules/material-design-icons/iconfont/material-icons.css:8:12: Can't resolve '../node_modules/material-design-icons/iconfont/MaterialIcons-Regular.woff2)%20format(%27woff2%27' in '/Users/json/OneDrive/MyProjects/ArtNgCore/src'
> 
>    6 |   src: local('Material Icons'),
>    7 |        local('MaterialIcons-Regular'),
> >  8 |        url(MaterialIcons-Regular.woff2) format('woff2'),
>      |            ^
>    9 |        url(MaterialIcons-Regular.woff) format('woff'),
>   10 |        url(MaterialIcons-Regular.ttf) format('truetype');
> 
> ERROR in ./node_modules/raw-loader!./node_modules/postcss-loader/lib??embedded!./node_modules/sass-loader/lib/loader.js??ref--8-3!./src/styles.scss
> (Emitted value instead of an instance of Error) CssSyntaxError: /Users/json/OneDrive/MyProjects/ArtNgCore/node_modules/material-design-icons/iconfont/material-icons.css:9:12: Can't resolve '../node_modules/material-design-icons/iconfont/MaterialIcons-Regular.woff)%20format(%27woff%27' in '/Users/json/OneDrive/MyProjects/ArtNgCore/src'
> 
>    7 |        local('MaterialIcons-Regular'),
>    8 |        url(MaterialIcons-Regular.woff2) format('woff2'),
> >  9 |        url(MaterialIcons-Regular.woff) format('woff'),
>      |            ^
>   10 |        url(MaterialIcons-Regular.ttf) format('truetype');
>   11 | }
>

**Comment by krilllind** [comment]
Same issue as @embryologist 
Referring to files via css url() without "" causes the build to crash.
This should work, as it has a different meaning when using for example sass.

Can confirm that it's not working in 1.7.1

**Comment by ShinDarth** [comment]
`1.7.1` is solving the issue for me, thanks a lot @clydin

**Comment by charlesc32** [comment]
1.7.1 did not fix the issue for me. I had to roll back to 1.6.0. I'm seeing the error on unquoted urls for fonts.

**Comment by krilllind** [comment]
@smoke Would you please reopen this issue, as mentioned above, unquoted urls in css and sass are not working.

**Comment by MrJmpl3** [comment]
Same error , please reopen this issue

**Comment by FriendOfTheNight** [comment]
Same issue with 1.7.1

**Comment by Polyterative** [comment]
Still having the issue with 1.7.2
My file:
```css

@font-face {
    font-family: 'Material Icons';
    font-style: normal;
    font-weight: 400;
    src: url('MaterialIcons-Regular.eot'); /* For IE6-8 */
    src: local('Material Icons'),
    local('MaterialIcons-Regular'),
    url('MaterialIcons-Regular.woff2') format('woff2'),
    url('MaterialIcons-Regular.woff') format('woff'),
    url('MaterialIcons-Regular.ttf') format('truetype');
}

.material-icons {
    font-family: 'Material Icons';
    font-weight: normal;
    font-style: normal;
    font-size: 24px; /* Preferred icon size */
    display: inline-block;
    line-height: 1;
    text-transform: none;
    letter-spacing: normal;
    word-wrap: normal;
    white-space: nowrap;
    direction: ltr;

    /* Support for all WebKit browsers. */
    -webkit-font-smoothing: antialiased;
    /* Support for Safari and Chrome. */
    text-rendering: optimizeLegibility;

    /* Support for Firefox. */
    -moz-osx-font-smoothing: grayscale;

    /* Support for IE. */
    font-feature-settings: 'liga';
}
```
