### ISSUE TITLE
Embed  loading-animation-css source inline into index.html head

### ISSUE THREAD

**Issue by xmlking** [angular/angular-cli#9767]
### Versions
```
Angular CLI: 1.6.5
Node: 9.5.0
OS: darwin x64
Angular: 5.2.3
```

### Repro steps
* preload.scss
* index.html
 

### Observed behavior
Preload animation css is loaded as part of other assets.  this might be too late for using it for showing loading animation for slow networks. 

### Desired behavior
we like to code the `loader`, `loader-inner line-scale` css in a file `preload.scss`  and have angular-cli provide an option to inline inject this css content into `index.html` header.

```html
<body class="default-app-background">
  <app-root>
    <!-- Pre-Bootstrap Loading animation -->
    <div class="loader">
      <div class="loader-inner line-scale">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </app-root>
</body>
```

preload.scss
```scss
@import "constants";

/* PRE LOADER
-------------------------------------------------- */
@import '~loaders.css/src/animations/line-scale';
@import '~loaders.css/src/animations/line-scale-pulse-out';


.loader {
  //background: $auxiliary;
  background: $loader_bg;
  display: table;
  height: 100%;
  max-width: 100%;
  position: absolute;
  width: 100%;
  z-index: 99999;

  .loader-inner {
    backface-visibility: hidden;
    display: table-cell;
    overflow: hidden;
    text-align: center;
    vertical-align: middle;
  }
}

```

### Mention any other details that might be useful (optional)

This best practice is described here:

https://medium.com/@tomastrajan/how-to-style-angular-application-loading-with-angular-cli-like-a-boss-cdd4f5358554
