### ISSUE TITLE
autoprefixer can not find grid areas when using @media

### ISSUE THREAD

**Issue by zurfyx** [angular/angular-cli#9829]
### Versions
```
Angular CLI: 1.7.2
Node: 9.4.0
OS: linux x64
Angular: 5.2.7
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.2
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.1
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

### Repro steps

Having `@media` tag prevents it from finding associated `grid-area`.

**✗** The following does output:

`WARNING in ./src/app/core/footer/footer.component.scss
(Emitted value instead of an instance of Error) autoprefixer: /.../footer.component.scss:28:6: Can not find grid areas: social`

footer.component.scss

```
@media (min-width: 550px) {
  footer {
      grid-template-areas:
        "social ..."
        "...";
    }
}

.social {
  grid-area: social;
}
```

**✓** The following does NOT output any warning:

```
footer {
    grid-template-areas:
      "social ..."
      "...";
}

.social {
  grid-area: social;
}
```

### Desired behavior

`@media` should not prevent SCSS from finding `grid-area` outside its scope.

### Other

Related: https://github.com/angular/angular-cli/issues/9502

**Comment by skix123** [comment]
I have the same issue.

**Comment by krodyrobi** [comment]
Same here

```
Angular CLI: 1.6.7
Node: 8.9.4
OS: win32 x64
Angular: 5.2.3
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cdk: 5.2.0
@angular/cli: 1.6.7
@angular/material: 5.2.0
@angular-devkit/build-optimizer: 0.0.42
@angular-devkit/core: 0.0.29
@angular-devkit/schematics: 0.0.52
@ngtools/json-schema: 1.1.0
@ngtools/webpack: 1.9.7
@schematics/angular: 0.1.17
typescript: 2.5.3
webpack: 3.10.0
```

**Comment by jmls** [comment]
anyone found a solution to this ?

**Comment by JesseZomer** [comment]
We've been using a combination of the two answers found here as a workaround: https://stackoverflow.com/questions/48588493/angular-5-and-css-grid-cannot-find-grid-areas-warning

**Comment by luchillo17** [comment]
Same issue here, except i got the `grid-template-areas` defined inside as well as outside:
```scss
.wrapper {
  height: 100%;
  display: grid;
  grid-gap: 0.5rem;
  grid-template-rows: 64px 1fr 1fr;
  grid-template-columns: 1fr 1fr;

  grid-template-areas:
    "header header"
    "board controls"
    "board controls";

  @media screen and (max-width: 700px) {
    grid-template-areas:
      "header header"
      "board board"
      "controls controls";
  }
}
```
Output:
![image](https://user-images.githubusercontent.com/9698639/38284312-340a6542-3780-11e8-8b8e-e770cf7c7ed3.png)
